#!/bin/bash
# $1, mac address, # $2, service time
# repository for caching during operation on
cd /run/shm

# delete expired service session
for tsh in `find . -cmin +$2 -name "UA*.sh"`;
do
   echo $tsh
   cat $tsh >> UA_`date +%Y%m%d`.log
   bash $tsh
   rm $tsh 
done

# prepare cut the firewall for mac and self-destroy
echo -e "sudo iptables -D internet -t mangle -m mac --mac-source $1 -j RETURN" \
        >> UA_`date '+%Y%m%d.%H%M'`.sh
