#!/bin/bash

confirm_to_continue "--------step.3 to set RASPBIAN mirror"
rc=$?; if [[ $rc == 0 ]]; then
 
echo_log "  change archive source from origine to KAIST mirror"
#change source list
ls -la /etc/apt/sources.list
 
module=$(head -n 1 /etc/apt/sources.list | awk '{print $3}')
echo "deb http://ftp.kaist.ac.kr/raspbian/raspbian/ $module main contrib non-free rpi" > /run/shm/s.d
cat /run/shm/s.d
if [ -e /etc/apt/sources.list.org ]
then
	sudo cp /etc/apt/sources.list.org /etc/apt/sources.list 
else
  	sudo cp /etc/apt/sources.list /etc/apt/sources.list.org
fi
 
sudo sh -c "sed -i 's/deb http/#deb http/g' /etc/apt/sources.list"
sudo sh -c "cat /run/shm/s.d /etc/apt/sources.list > /etc/apt/sources.list.net"
cat /etc/apt/sources.list.net
sudo sh -c "cat /run/shm/s.d /etc/apt/sources.list > /etc/apt/sources.list.net"
sudo mv /etc/apt/sources.list.net /etc/apt/sources.list
 
ls -la /etc/apt/sources.list
cat /etc/apt/sources.list
# end of script
 
sudo apt-get update
# end of script
 
# sudo apt-get -y upgrade
sudo apt-get clean
# end of script
else
	sudo apt-get update
fi
