#!/bin/bash

confirm_to_continue "--------step.4 to install file share(SAMBA)"
rc=$?; if [[ $rc == 0 ]]; then
echo "Install samba package to share document over windows file sharing protocol"
sudo apt-get -y install samba samba-common-bin
# end of script
 
sudo smbpasswd -a pi
# end of script
 
cat << EOF > smb.tmp
[pi]
path = /home/pi
comment = PI SAMBA SERVER
writable = no
browseable = yes
create mask = 0777
#public = yes
read list = pi
write list = pi
EOF
sudo sh -c "cat smb.tmp >> \/etc\/samba\/smb.conf"
rm -rf ./smp.tmp
 
tail /etc/samba/smb.conf
# end of script
 
fi
