#!/bin/bash

confirm_to_continue "------- step.7 to install Internet Photoframe(SurpriseBox)"
rc=$?; if [[ $rc == 0 ]]; then
 
#remote key input
cd ~
ln -sfT ~/smart-board/.installer/core/rinput ./rinput && cd ~/rinput
make
sudo make install > /dev/null 2&>1 &
wait $! ## waiting make install
# end of script
# schedule job
cd ~
ln -sfT ~/smart-board/.installer/core/scheduler ./scheduler && cd ~/scheduler
cp Makefile_pi Makefile
make
sudo make install > /dev/null 2&>1 &
wait $! ## waiting make install
 
sudo sh -c "echo -n > /etc/hive/tasks/schedule.tasks"
sudo chmod 666 /etc/hive/tasks/schedule.tasks
sudo chmod 777 /etc/hive/tasks
sudo service timeworks start
# end of script

# signage configuration
cd ~
ln -sfT ~/smart-board ~/signage && cd ~/signage
# end of script
 
# set default landing page
cd ~/signage/.installer
sudo ln -sfT ~/smart-board /var/www/signage
sudo cp res/index.html /var/www/index.html
 
# set permission
chmod -R g+w ~/signage/custom/sample
chmod -R g+w ~/signage/validator
 
# set folders
mkdir -p ~/media/slide
mkdir -p ~/media/playlist
mkdir -p ~/media/captions
ln -sfT ~/media/captions ~/media/playlist/captions
mkdir -p ~/media/thumbs
mkdir -p ~/media/video
mkdir -p ~/media/info
 
# open to web
sudo ln -sfT ~/media /var/www/media
chmod -R 775 ~/media
# end of script

# open usb access
sudo chmod -R 755 /media
 
sudo mkdir -p /etc/hive/signage
sudo ln res/feh.sh /etc/hive/signage/feh.sh
sudo ln res/omx.sh /etc/hive/signage/omx.sh
sudo chmod -R 775 /etc/hive/signage
ls -la /etc/hive/signage/
# end of script
 
sudo mkdir -p /etc/hive/default
sudo ln -sfT ~/signage /etc/hive/default/signage
ls -al /etc/hive/default/signage
# end of script
 
fi
