#!/bin/bash

confirm_to_continue "------- step.8 to install suppliment package(Utilities)"
rc=$?; if [[ $rc == 0 ]]; then
 
# additional network packages
sudo apt-get -y install conntrack
# end of script
 
sudo mkdir -p /etc/hive/bin
sudo cp res/cutconnect /etc/hive/bin/cutconnect
sudo cp res/rmtrack /etc/hive/bin/rmtrack
sudo cp res/shellcmd /etc/hive/bin/shellcmd
sudo chmod -R 755 /etc/hive/bin
# end of script
 
sudo sh -c "echo 'www-data ALL = NOPASSWD: /etc/hive/bin/rmtrack' >> /etc/sudoers.d/sign_sudoers"
sudo sh -c "echo 'www-data ALL = NOPASSWD: /etc/hive/bin/cutconnet' >> /etc/sudoers.d/sign_sudoers"
sudo sh -c "echo 'www-data ALL = NOPASSWD: /sbin/iptables' >> /etc/sudoers.d/sign_sudoers"
sudo sh -c "echo 'www-data ALL = NOPASSWD: /usr/sbin/arp' >> /etc/sudoers.d/sign_sudoers"
 
cat /etc/sudoers.d/sign_sudoers
# end of script
 
cd ~
sudo apt-get -y install evtest imagemagick miniupnpc
# end of script
 
fi
