#!/bin/bash

confirm_to_continue "------- step.10 Change to AP enable mode and another setting"
rc=$?; if [[ $rc == 0 ]]; then
#WI-FI enable
cd ~/ap
sudo ./set_ap.sh enable
echo "ap is enabled.."
ap=enable
fi
# end of script
